### PR TITLE
Allow to Tune Frequency, Gain and Channel Width

### PR DESCRIPTION
**Pull request by iceman73**
Put back to main rtl_433 Lib to pull latest supports parsers
Added configuration Options to Set Frequency, Gain, and Frequency Offset
Set Base config to work for GE/Interlogix Wireless Contact Sensors commonly found in newer homes that have wireless alarms.

### CODE REVIEW

**Comment by iceman73** [comment]
@james-fry I found that there is still an issue when using the source rtl_433, where after 2 hours or so, it stops working due to the alarm(1) checks. I forked the rtl_433 and changed the alarm(1) to alarm(3) in rtl_433.c, and so far seems not to disconnect. I will monitor throughout the day and update you if this is the fix needed and suggest a merge back to the main rtl_433.

You might want to change the docker file to pull from my forked repo, or go back to your forked repo of rtl_433. If you pull from my repo it will update to my forked rtl_433 with the alarm timer change.

**Comment by james-fry** [comment]
@iceman73 Thanks Chris. Let me know how you get on... I will shortly bring my fork of rtl433 up to parity with the master, but keep my alterations to comment out the alarms. I was less diligent than you and was not able to dedicate the time to find optimum value by trial and error. Mine has been up for months :)

**Comment by iceman73** [comment]
Looks like 3 is the Key just hit 14 hours and stable, will report back after 24 hrs

**Comment by iceman73** [comment]
Ok that setting in rtl_433 has been running stable with alarm set to 3 for 48 hrs now. 

I will update readme today and issue new pull request

**Comment by iceman73** [comment]
@james-fry  Alarm change was merged so I will update make to mainline rtl_433 and update readme tonight

**Comment by james-fry** [comment]
Thanks Chris. Nice job!

**Pull request merged**
